### PR TITLE
js/stdlib: start on encodeParameter

### PR DESCRIPTION
**Pull request by AlexKnauth**
The initial version supports `uint256`, `bool`, `address`, and `bytes`.

The `uint256` and `address` types both use `BNtoHex` to emit 32 bytes in big-endian encoding, which for address is equivalent to 20 bytes big-endian lefted-padded with zeros to 32 bytes.

The `bool` type uses `b ? 1 : 0` to convert to a number first, and then uses `BNtoHex` because that too needs to be left-padded to 32 bytes according to the [documentation](https://solidity.readthedocs.io/en/v0.5.9/abi-spec.html?highlight=abi.encode#formal-specification-of-the-encoding).

The `bytes` type uses `BNtoHex` to emit the length as the first 32 bytes, and then appends the string padded to the right until the next multiple of 32 bytes. There is a `parameter.length / 2` at the beginning to convert from js-length to logical-length, and a `2 * kpad` at the end to convert from logical-length back to js-length.

### CODE REVIEW

**Comment by fare** [comment]
That's not how dynamic parameters work. See the example with `sam` in https://solidity.readthedocs.io/en/v0.5.3/abi-spec.html

**Comment by AlexKnauth** [comment]
From `encodeParameter` it seems I am returning the bytes for the "data part", where the examples you're referring to have a offset in the parameter list, pointing to the place where the data part will be put later. Since this is non-local, it doesn't fit in a "single parameter" function, but does fit in a "multiple parameters" function.

So to fix this:
 * perhaps the function I called `encodeParameter` should be renamed to `encodeDataPart`
 * the `encodeParameters` function needs to call `encodeDataPart` for dynamic parameters, and as a second pass, append those data parts at the end and return the output with the correct offsets to them

**Comment by fare** [comment]
It's not about single vs multiple parameters. It's about fixed size types vs dynamic size types.
All parameters take 32 bytes in the fixed size portion.
Those with a dynamic size are encoded as the offset to the actual data, starting with size in number of items, then have an array for the fixed size of these items, and recurse.

**Comment by AlexKnauth** [comment]
Oh, that's right. I misinterpreted how this was specified in the `head` and `tail` functions in the tuple section:
```
head(X(i)) = enc(len( head(X(1)) ... head(X(k)) tail(X(1)) ... tail(X(i-1)) ))
```
```
tail(X(i)) = enc(X(i))
```

**Comment by fare** [comment]
That's why I suggested looking at the web3 sources at https://github.com/ethereum/web3.js/blob/2.x/packages/web3-eth-abi/src/AbiCoder.js (which actually imports the hard parts from https://github.com/ethers-io/ethers.js/blob/master/utils/abi-coder.js ) instead of reinventing your own incompatible reading of it. Apparently, these guys are into baroque complexity, so maybe the advice wasn't so useful in the end.

One advantage of going the factory way is that we were eschewing this complexity. But since we only need `bytes` support for now, you can special case something simple.

My understanding is that you have an extensible vector of bytes, wherein you allocate chunks as multiple of 32-byte words with a simple `brk`-style pointer at the end. For every "fixed" block of `n` fields, you get a chunk of size `n*32`. Then for each "dynamic" argument of size `d`, you allocate a block of size `(1+d)*32` and you recurse, with special case for bytes and strings, where you pack the data big-endianly and don't need to recurse.

**Comment by AlexKnauth** [comment]
Here's what I have so far for handling dynamic types and using the offsets in the head:
https://github.com/AlacrisIO/alacrity/commit/ff560ba4eb3ea7c73700d81cd46cf8a0bf1a0b98

**Pull request merged**
